### ISSUE TITLE
`Error: undefined method `split' for nil:NilClass` when using `--show_resource_diff`

### ISSUE THREAD

**Issue by alexjfisher** [camptocamp/puppet-catalog-diff#32]
```
Debug: Resource diff: class[Profile::Webapps]
#<Thread:0x00007fefc45f3c80@/home/fishera/.puppetlabs/etc/code/modules/catalog_diff/lib/puppet/face/catalog/diff.rb:146 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	4: from /home/fishera/.puppetlabs/etc/code/modules/catalog_diff/lib/puppet/face/catalog/diff.rb:150:in `block (5 levels) in <top (required)>'
	3: from /home/fishera/.puppetlabs/etc/code/modules/catalog_diff/lib/puppet/catalog-diff/differ.rb:100:in `diff'
	2: from /home/fishera/.puppetlabs/etc/code/modules/catalog_diff/lib/puppet/catalog-diff/comparer.rb:33:in `compare_resources'
	1: from /home/fishera/.puppetlabs/etc/code/modules/catalog_diff/lib/puppet/catalog-diff/comparer.rb:33:in `each'
/home/fishera/.puppetlabs/etc/code/modules/catalog_diff/lib/puppet/catalog-diff/comparer.rb:60:in `block in compare_resources': undefined method `split' for nil:NilClass (NoMethodError)
Error: undefined method `split' for nil:NilClass
Error: Try 'puppet help catalog diff' for usage
```

**Comment by alexjfisher** [comment]
I tried with an older agent, (6.13), but same issue.

**Comment by alexjfisher** [comment]
Since https://github.com/camptocamp/puppet-catalog-diff/pull/13/commits/35a34985eb83b3679cc042e251794e52b05b27f9 `str_diff` can return `nil`

**Comment by alexjfisher** [comment]
Backing out the changes in that commit appears to fix this issue.

**Comment by alexjfisher** [comment]
I could 'fix' this as follows.  Can't help think that this code shouldn't have been called when it was and I'm hiding some other bug though.
```patch
--- a/lib/puppet/catalog-diff/comparer.rb
+++ b/lib/puppet/catalog-diff/comparer.rb
@@ -54,10 +54,17 @@ module Puppet::CatalogDiff
         if options[:show_resource_diff]
           Puppet.debug("Resource diff: #{resource[:resource_id]}")
 
-          diff_array = str_diff(
+          diff = str_diff(
             Puppet::CatalogDiff::Formater.new.resource_to_string(resource),
             Puppet::CatalogDiff::Formater.new.resource_to_string(new_resource),
-          ).split("\n")
+          )
+
+          if diff
+            diff_array = diff.split("\n")
+          else
+            diff_array = []
+          end
+
           if diff_array.size >= 3
             string_differences[resource[:resource_id]] = diff_array[3..-1]
           else
```

**Comment by alexjfisher** [comment]
FWIW, for me str_diff was returning `nil` for me here. https://github.com/camptocamp/puppet-catalog-diff/blob/967bd3ade1c99ac48a14fabcdfb14926f529067c/lib/puppet/catalog-diff/comparer.rb#L142

**Comment by raphink** [comment]
Another option could be to return an empty string instead of `nil`?

**Comment by alexjfisher** [comment]
yeah probably.  I'm not hitting this anymore since https://github.com/camptocamp/puppet-catalog-diff/pull/33 was merged.

**Comment by alexjfisher** [comment]
@raphink Could we reopen this?  I've hit it again, but this time think can reproduce it properly.

**Comment by alexjfisher** [comment]
If the only change in a class being included is the type of parameter from a float type to a string type, eg.
 ```
❯ git diff catalog_diff_old catalog_diff_new

─────────────────────────────┐
manifests/site.pp:32: File { │
─────────────────────────────┘
  32┊  32│}
  33┊  33│
  34┊  34│class test(
  35┊    │  Float $version = 10.0
    ┊  35│  String $version = "10.0"
  36┊  36│) {
  37┊  37│
  38┊  38│}
```

Then the class resource will be 'different', but `nil` will be returned https://github.com/camptocamp/puppet-catalog-diff/blob/967bd3ade1c99ac48a14fabcdfb14926f529067c/lib/puppet/catalog-diff/comparer.rb#L142
as the formatter will format both a Float and a String the same. https://github.com/camptocamp/puppet-catalog-diff/blob/967bd3ade1c99ac48a14fabcdfb14926f529067c/lib/puppet/catalog-diff/formater.rb#L12
